import Head from "next/head";
import WelcomeScreen from "./components/WelcomeScreen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>It's just practicing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WelcomeScreen />
    </div>
  );
}
